/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:4d1e7d58-6fb0-4974-b79d-4b2350d96deb",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_MjWOHZrWl",
    "aws_user_pools_web_client_id": "2l8p1rnprmp8j4lbtqjp5dn51r",
    "oauth": {}
};


export default awsmobile;
